spring.application.name=raquel
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/eventos_acessiveis
spring.datasource.username=postgres
spring.datasource.password=abc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.path=/swagger-ui.html
spring.main.allow-bean-definition-overriding=true
